org: jamesargy6
app: data-scraper-app
service: data-scraper-app

provider:
  iam:
    deploymentRole:
	  Fn::Sub: 'arn:aws:iam::${AWS::AccountId}:role/data-scraper-app-CloudFormationExecutionRole'

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: handler.hello
