app: data-scraper-app
service: data-scraper-app

plugins:
  - serverless-plugin-typescript

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    deploymentRole: 'arn:aws:iam::104843235006:role/data-scraper-app-CloudFormationExecutionRole'

functions:
  getGameDates:
    handler: src/handler.getGameDates
  
  getBatterPlayMap:
    handler: src/handler.getBatterPlayMap
