app: data-scraper-app 
service: data-scraper-app

plugins:
  - serverless-plugin-typescript
  - serverless-step-functions

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    deploymentRole: 'arn:aws:iam::104843235006:role/data-scraper-app-CloudFormationExecutionRole'

functions:
  getGames:
    handler: src/handler.getGames
  
  getPlays:
    handler: src/handler.getPlays
  
  getGameDetails:
    handler: src/handler.getGameDetails

stepFunctions:
  stateMachines:
    ScrapeDataForYear:
      type: EXPRESS
      loggingConfig:
        level: ALL
        includeExecutionData: true
        destinations:
          - Fn::GetAtt: [ScrapeDataForYearLogGroup, Arn]
      definition:
        StartAt: GetGames
        States:
          GetGames:
            Type: Task
            Resource:
              Fn::GetAtt: [getGames, Arn]
            Next: ScrapeDataForAllGames
          ScrapeDataForAllGames:
            Type: Map
            Iterator:
              StartAt: ScrapeGameDetails
              States:
                ScrapeGameDetails:
                  Type: Parallel
                  Next: FinalState
                  Branches:
                  - StartAt: GetPlays
                    States:
                      GetPlays:
                        Type: Task
                        Resource:
                          Fn::GetAtt: [getPlays, Arn]
                        ResultPath: $.plays
                        Next: WritePlaysToDynamo
                      WritePlaysToDynamo:
                        Type: Task
                        Resource: arn:aws:lambda:us-west-2:104843235006:function:data-storage-${sls:stage}-writePlaysToDynamo
                        End: true
                  - StartAt: GetGameDetails
                    States:
                      GetGameDetails:
                        Type: Task
                        Resource:
                          Fn::GetAtt: [getGameDetails, Arn]
                        End: true
                FinalState:
                  Type: Pass
                  End: true
            ResultPath: null
            End: true

resources:
  Resources:
    ScrapeDataForYearLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: !Join [ /, [ stepFunctions, ScrapeDataForYear]]
