app: data-scraper-app 
service: data-scraper-app

plugins:
  - serverless-plugin-typescript
  - serverless-step-functions

custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: './tsconfig.json'

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    deploymentRole: 'arn:aws:iam::104843235006:role/data-scraper-app-CloudFormationExecutionRole'

functions:
  getGames:
    handler: src/handler.getGames
    timeout: 20
  
  getPlays:
    handler: src/handler.getPlays
  
  getGameDetail:
    handler: src/handler.getGameDetail
