app: data-scraper-app
service: data-scraper-app

plugins:
  - serverless-plugin-typescript
  - serverless-step-functions

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    deploymentRole: 'arn:aws:iam::104843235006:role/data-scraper-app-CloudFormationExecutionRole'

functions:
  getGameDates:
    handler: src/handler.getGameDates
  
  getPlays:
    handler: src/handler.getPlays

stepFunctions:
  stateMachines:
    ScrapeDataForYear:
      type: EXPRESS
      loggingConfig:
        level: ALL
        includeExecutionData: true
      definition:
        StartAt: GetGameDates
        States:
          GetGameDates:
            Type: Task
            Resource: "arn:aws:states:::lambda:invoke"
            Parameters:
              Payload.$: $
              FunctionName:
                Fn::GetAtt: [getGameDates, Arn]
            OutputPath: $.Payload
            Next: ScrapeDataForAllGames
          ScrapeDataForAllGames:
            Type: Map
            Iterator:
              StartAt: GetPlays
              States:
                GetPlays:
                  Type: Task
                  Resource: "arn:aws:states:::lambda:invoke"
                  Parameters:
                    Payload.$: $
                    FunctionName:
                      Fn::GetAtt: [getPlays, Arn]
                  OutputPath: $.Payload
                  End: true
            ResultPath: null
            End: true
