app: data-scraper-app
service: data-scraper-app

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    deploymentRole:
      Fn::Sub: 'arn:aws:iam::${AWS::AccountId}:role/data-scraper-app-CloudFormationExecutionRole'

functions:
  hello:
    handler: handler.hello
