app: data-storage 
service: data-storage

frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    deploymentRole: 'arn:aws:iam::104843235006:role/data-scraper-app-CloudFormationExecutionRole'

functions:
  writePlaysToDynamo:
    handler: src/handler.writePlaysToDynamo
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: "Allow"        
        Action:
          - dynamodb:PutItem
          - dynamodb:BatchWriteItem
        Resource: arn:aws:dynamodb:us-west-2:*:table/bts-play
  writeGameDetailToDynamo:
    handler: src/handler.writeGameDetailToDynamo
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: "Allow"        
        Action:
          - dynamodb:PutItem
          - dynamodb:BatchWriteItem
        Resource: arn:aws:dynamodb:us-west-2:*:table/bts-game
  readGameDetailFromDynamo:
    handler: src/handler.readGameDetailFromDynamo
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: "Allow"        
        Action:
          - dynamodb:GetItem
        Resource: arn:aws:dynamodb:us-west-2:*:table/bts-game

resources:
  Resources:
    playTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: bts-play
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: batterId
            AttributeType: N
          - AttributeName: pitcherId
            AttributeType: N
          - AttributeName: playIndex
            AttributeType: S
        KeySchema:
          - AttributeName: batterId
            KeyType: HASH
          - AttributeName: playIndex
            KeyType: RANGE
        GlobalSecondaryIndexes: 
        - IndexName: pitcherId_idx
          KeySchema:
          - AttributeName: pitcherId
            KeyType: HASH
          - AttributeName: playIndex
            KeyType: RANGE
          Projection:
            ProjectionType: ALL
    gameDetailTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: bts-game
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: gameIndex
            AttributeType: S
        KeySchema:
          - AttributeName: gameIndex
            KeyType: HASH
