app: data-storage 
service: data-storage

frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    deploymentRole: 'arn:aws:iam::104843235006:role/data-scraper-app-CloudFormationExecutionRole'

functions:
  writePlaysToDynamo:
    handler: src/handler.writePlaysToDynamo
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: "Allow"        
        Action:
          - dynamodb:PutItem
          - dynamodb:BatchWriteItem
        Resource: arn:aws:dynamodb:us-west-2:*:table/bts-play
  writeGameDetailToDynamo:
    handler: src/handler.writeGameDetailToDynamo
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: "Allow"        
        Action:
          - dynamodb:PutItem
          - dynamodb:BatchWriteItem
        Resource: arn:aws:dynamodb:us-west-2:*:table/bts-game-detail

resources:
  Resources:
    playTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: bts-play
        AttributeDefinitions:
          - AttributeName: tx_batter_id
            AttributeType: S
          - AttributeName: play_index
            AttributeType: S
        KeySchema:
          - AttributeName: tx_batter_id
            KeyType: HASH
          - AttributeName: play_index
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 10
        TimeToLiveSpecification:
          Enabled: True
          AttributeName: ttl
    gameDetailTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: bts-game-detail
        AttributeDefinitions:
          - AttributeName: tx_id
            AttributeType: S
          - AttributeName: game_index
            AttributeType: S
        KeySchema:
          - AttributeName: tx_id
            KeyType: HASH
          - AttributeName: game_index
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 10
        TimeToLiveSpecification:
          Enabled: True
          AttributeName: ttl
