app: data-storage 
service: data-storage

frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    deploymentRole: 'arn:aws:iam::104843235006:role/data-scraper-app-CloudFormationExecutionRole'

functions:
  writePlaysToDynamo:
    handler: src/handler.writePlaysToDynamo
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: "Allow"        
        Action:
          - dynamodb:PutItem
          - dynamodb:BatchWriteItem
        Resource: "arn:aws:dynamodb:us-west-2:*:table/bts_play"

resources:
  Resources:
    playTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: bts_play
        AttributeDefinitions:
          - AttributeName: tx_id
            AttributeType: S
          - AttributeName: tx_batter_id
            AttributeType: S
          - AttributeName: play_index
            AttributeType: S
        KeySchema:
          - AttributeName: tx_id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: tx_id
            KeySchema:
              - AttributeName: tx_batter_id
                KeyType: HASH
              - AttributeName: play_index
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 10
              WriteCapacityUnits: 10
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 10
