app: data-storage
service: data-storage

frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    deploymentRole: 'arn:aws:iam::104843235006:role/data-scraper-app-CloudFormationExecutionRole'

functions:
  writePlaysToDynamo:
    handler: src/handler.writePlaysToDynamo
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: "Allow"        
        Action:
          - dynamodb:PutItem
          - dynamodb:BatchWriteItem
        Resource: "arn:aws:dynamodb:us-west-2:*:table/bts-play"

resources:
  Resources:
    playTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: bts-play
        AttributeDefinitions:
          - AttributeName: playerId
            AttributeType: S
          - AttributeName: playId
            AttributeType: S
        KeySchema:
          - AttributeName: playerId
            KeyType: HASH
          - AttributeName: playId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 10
