name: data-scraper-app-build

on:
  pull_request:
    branches: 
      - main
    paths:
      - 'data-scraper-app/**'
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        shell: bash
        working-directory: data-scraper-app

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: './data-scraper-app/.nvmrc'

      - name: Install packages
        run: npm ci

      - name: Test
        run: npm run test